name: Build and publish Docker image

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sam_blocks_inventory:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/sam_blocks_inventory:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

      - name: Optional Fly deploy
        if: ${{ secrets.FLY_API_TOKEN != '' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          # This uses flyctl to deploy the image; requires flyctl to be installed
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="${HOME}/.fly"
          export PATH="${FLYCTL_INSTALL}/bin:$PATH"
          flyctl auth token "$FLY_API_TOKEN"
          # set your app name in fly.toml or replace with your app name
          flyctl deploy --image "${{ secrets.DOCKERHUB_USERNAME }}/sam_blocks_inventory:latest" --config fly.toml
